### ISSUE TITLE
todo

### ISSUE THREAD

**Issue by piotrek1234** [piotrek1234/app-manager#4]
- [ ] przycisk budowania
- [ ] zmiana gałęzi git
- [ ] podgląd outputu
- [ ] poprawić widoczność listy apek (nie mieści się exit code w ubuntu 20)
- [ ] naprawić ikonę aplikacji w ubuntu 20
- [ ] dodać liczbę odpalonych apek w ikonie aplikacji
- [ ] poszerzyć białe tło liczby apek w ikonie na pasku przy ≥10
